---
- hosts: default-master
  vars:
    http_port: 80
  user: root
  gather_facts: no
  tasks:
  - name: get gridftp
    get_url: url=http://www.globus.org/ftppub/latest-stable/gt-latest-stable-all-source-installer.tar.gz dest=/root
  - name: unpack gridftp
    command: tar xfz gt-latest-stable-all-source-installer.tar.gz
  - name: mkdir
    command: ls creates=/usr/local/globus-5.0.4
  - name: export GLOBUS_LOCATION
    action: shell export GLOBUS_LOCATION=/usr/local/globus-5.0.4
  - name: configure
    command: chdir=/root/gt5.0.4-all-source-installer/ ./configure --prefix=/usr/local/globus-5.0.4
  - name: make 
    command: chdir=/root/gt5.0.4-all-source-installer make 
  - name: make install
    command: chdir=/root/gt5.0.4-all-source-installer make install
