---
- hosts: default-master
  vars:
    http_port: 80
  user: root
  gather_facts: no
  tasks:
  - name: Install MySQL
    yum: name=mysql-server state=latest
  - name: Start MySQL
    service: name=mysqld state=started
  - name: Create Adatao user
    command: mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO adatao@localhost identified by 'ada!@#';GRANT ALL PRIVILEGES ON *.* TO adatao@'%' identified by 'ada!@#';"
  - name: Link hive-0.9.0-bin to /root/hive/build/dist if not existed
    command: ln -s /root/hive/build/dist /root/hive-0.9.0-bin creates=/root/hive-0.9.0-bin
  - name: Download MySQL JDBC driver
    get_url: url=http://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.24/mysql-connector-java-5.1.24.jar dest=/root/hive-0.9.0-bin/lib/mysql-connector-java-5.1.24.jar
  - name: Copy Hive configuration
    copy: src=../conf/hive-site.xml dest=/root/hive-0.9.0-bin/conf/hive-site.xml backup=yes 
  - name: Copy shark configuration
    copy: src=../conf/shark-env.sh dest=/root/shark/conf/shark-env.sh backup=yes
