---
# Install Adatao pInsights

- hosts: default-master
  user: root
  gather_facts: no

  vars:

  - pInsights_version: pInsights-proto
  - pInsights_dir: /root/pInsights
  - pInsights_venv_dir: /root/pInsights/venv
  - pInsights_notebook_dir: /root/pInsights/notebooks
  - pInsights_log_file: /mnt/log/pInsights.log

  # by default, pInsights runs on pAnalytics master instance
  - pAnalytics_host: localhost
  - pAnalytics_port: 7911

  tasks:

  - name: Ensure python2.7 and build tools is installed
    yum: name={{item}} state=installed
    with_items:
      - make
      - automake
      - gcc
      - gcc-c++
      - python27-devel
      - ncurses-devel
      - readline-devel
      - freetype-devel.x86_64
      - libpng-devel
      - libxml2-devel

  - name: Download the get-pip.py script
    get_url: url=https://raw.github.com/pypa/pip/master/contrib/get-pip.py dest=/mnt/get-pip.py

  - name: install pip2.7
    command: /usr/bin/python2.7 /mnt/get-pip.py creates=/usr/bin/pip2.7

  - name: install virtualenv-2.7
    command: /usr/bin/pip2.7 install virtualenv creates=/usr/bin/virtualenv-2.7

  - name: creates virtualenv for pInsights
    command: /usr/bin/virtualenv-2.7 {{pInsights_venv_dir}} creates={{pInsights_venv_dir}}

  # For this task to work, make sure this playbook is invoked with ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no -o ForwardAgent=yes"
  #- name: fetch pInsights code from Github, version = "{{pInsights_version}}", dest="{{pInsights_dir}}"
  #  git: repo=git@github.com:adatao/pInsights.git dest={{pInsights_dir}} version={{pInsights_version}}
  #  connection: ssh

  - name: install pInsights into pInsights virtualenv
    command: '{{ pInsights_venv_dir }}/bin/pip install -e ".[notebook]" chdir={{pInsights_dir}} creates={{ pInsights_venv_dir}}/bin/ipython'

  - name: install rpy2, numpy and matplotlib into pInsights virtualenv
    command: '{{pInsights_venv_dir }}/bin/pip install {{item}}'
    with_items:
      - numpy
      - matplotlib
      - rpy2

  - name: deploy the pInsights run script
    template: src=../bin/run-pInsights-server.sh dest={{pInsights_dir}}/run-pInsights-server.sh mode=0744

  - name: ensure pInsights notebook storage dir exists
    file: name={{pInsights_notebook_dir}} state=directory

  - name: ensure correct pInsights notebook dir configuration
    lineinfile:
      dest='{{ pInsights_dir }}/profile_adatao/ipython_notebook_config.py'
      regexp=/^c.NotebookManager.notebook_dir.*/
      line='c.NotebookManager.notebook_dir = "{{pInsights_notebook_dir}}"'
      state=present

  #- name: Install deprecated-but-still-in-use Adatao BigR client package
  #  command: R -q -e "install.packages('adatao.bigr', repos=c('http://canary.adatao.com:8090/R'))" creates=/usr/lib64/R/library/adatao.bigr

  - name: Install Adatao pAnalytics R client package
    command: R -q -e "install.packages('adatao', repos=c('http://canary.adatao.com:8090/R'))" creates=/usr/lib64/R/library/adatao

  - name: Ensure required R packages are installed
    command: R -q -e "install.packages('{{ item }}', contriburl=contrib.url('http://cran.cnr.Berkeley.edu/'))" creates=/usr/lib64/R/library/{{ item }}
    with_items:
      - ggplot2
      - googleVis
      - yaml
      - XML
      - devtools

  - name: Install rCharts from github public repo
    command: R -q -e "require(devtools); install_github('rCharts', 'adatao')" creates=/usr/lib64/R/library/rCharts

# for some reason this always hangs, failing to kill the running ipython process (this script works fine manually)
#  - name: start pInsights
#    command: /mnt/pInsights/run-pInsights-server.sh
