---
#   Install Spark
#     ansible-playbook -i <node-list> --extra-vars "spark_version=v0.7.3-adatao"

- hosts: default-*
  user: root
  gather_facts: no
  
  vars:
    spark_version: v0.7.3-adatao
    dir: /mnt  
  tasks:
  # For this task to work, make sure this playbook is invoked with ANSIBLE_SSH_ARGS="-o StrictHostKeyChecking=no -o ForwardAgent=yes"
  - name: Download Spark ${spark_version}
    git: repo=git@github.com:adatao/spark.git dest=${dir}/spark-${spark_version} version=${spark_version}
    connection: ssh
    
  - name: Compile Spark
    command: sbt/sbt clean compile chdir=${dir}/spark-${spark_version}
    
  - name: Copy configuration
    copy: src=../conf/spark-env.sh dest=${dir}/spark-${spark_version}/conf/spark-env.sh group=root mode=644 
