---
# Install R

- hosts: default-*
  user: root
  gather_facts: no

  vars:
    key_name: "{{ lookup('env','admin_ssh_key') }}"

  tasks:

  - name: Ensure Rserve is started
    script: ../bin/start-rserve.sh
