---
- hosts: default*
  vars:
    http_port: 80
  user: root
  tasks:
  - name: Download scala-2.9.3
    get_url: url=http://www.scala-lang.org/downloads/distrib/files/scala-2.9.3.tgz dest=/root/scala-2.9.3.tgz
  - name: Unzip scala-2.9.3
    command: tar xvzf scala-2.9.3.tgz creates=/root/scala-2.9.3
  - name: Remove scala-2.9.2
    file: path=/root/scala-2.9.2 state=absent 
  - name: Link old scala to the new
    file: src=/root/scala-2.9.3 path=/root/scala-2.9.2 state=link 

  - name: Install Java 7
    yum: name=java-1.7.0-openjdk-devel state=present
  - name: Remove Java 6
    yum: name=java-1.6.0-openjdk state=absent
  - name: Link Java 6 => Java 7
    file: src=/etc/alternatives/java_sdk_1.7.0/ path=/usr/lib/jvm/java-1.6.0 state=link 
  - name: Link Java 6 => Java 7
    file: src=/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.25.x86_64 path=/usr/lib/jvm/java-1.6.0-openjdk.x86_64 state=link 
  - name: Link Java 6 => Java 7
    file: src=/etc/alternatives/jre-1.7.0/ path=/usr/lib/jvm/jre-1.6.0 state=link 
  - name: Link Java 6 => Java 7
    file: src=/etc/alternatives/jre_1.7.0/ path=/usr/lib/jvm/jre-1.6.0-openjdk.x86_64 state=link 
  - name: Export JAVA_HOME
    action: shell /bin/echo -e "export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk.x86_64\n" >> /root/.bash_profile
  - name: Update JAVA_HOME for Hadoop
    lineinfile: dest=/root/ephemeral-hdfs/conf/hadoop-env.sh regexp='^export JAVA_HOME' line='export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk.x86_64'

  - name: Remove old spark backup if existed
    file: path=/root/spark-backup state=absent
  - name: Backup current Spark
    command: mv /root/spark /root/spark-backup removes=/root/spark
  - name: Download latest Spark
    get_url: url=http://www.spark-project.org/download-spark-0.7.2-prebuilt-hadoop1 dest=/root/download-spark-0.7.2-prebuilt-hadoop1
  - name: Unzip Spark
    command: tar xvzf download-spark-0.7.2-prebuilt-hadoop1
  - name: Rename spark 0.7.2 => spark
    command: mv /root/spark-0.7.2 /root/spark creates=/root/spark
  - name: Copy old configuration
    command: cp /root/spark-backup/conf/spark-env.sh /root/spark/conf removes=/root/spark-backup/conf/spark-env.sh

  - name: Remove old shark backup if existed
    file: path=/root/shark-backup state=absent
  - name: Backup current Shark
    command: mv /root/shark /root/shark-backup removes=/root/shark
  - name: Download latest Shark
    get_url: url=http://spark-project.org/download/shark-0.7.0-hadoop1-bin.tgz dest=/root/shark-0.7.0-hadoop1-bin.tgz
  - name: Unzip Shark
    command: tar xvzf shark-0.7.0-hadoop1-bin.tgz creates=/root/shark-0.7.0
  - name: Rename shark 0.7.0 => shark
    command: mv /root/shark-0.7.0 /root/shark creates=/root/shark
  - name: Copy old configuration
    command: cp /root/shark-backup/conf/shark-env.sh /root/shark/conf removes=/root/shark-backup/conf/shark-env.sh
